apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  name: kafka-channel
  labels:
    app: kafka-channel
    app.kubernetes.io/component: kafka-channel
    app.kubernetes.io/instance: kafka-channel
    app.kubernetes.io/name: kafka-channel
    app.kubernetes.io/part-of: channel-demo
spec:
  numPartitions: 1
  replicationFactor: 3
  retentionDuration: PT168H
